headerMapping = {
    # "{0": "Unknown: 16",
    # "~0": "Length unit",
    # "~1": "Mass unit",
    # "~2": "Unknown: 4",
    # "~3": "Unknown: 3",
    # "Bt": "Unknown: 2, it has something to do with the athlete mode. When I set male athelete it is 2, when I set male it is 0",
    "Wk": "Body mass",
    "MI": "Body mass index (BMI)",
    # "MO": "Model",
    "DT": "Measurement Date",
    "Ti": "Measurement Time",
    "GE": "Gender",
    "AG": "Age",
    "Hm": "Height",
    # "AL": "Activity Level",
    "FW": "Global fat %",
    "Fr": "Arm fat (right) %",
    "Fl": "Arm fat (left) %",
    "FR": "Leg fat (right) %",
    "FL": "Leg fat (left) %",
    "FT": "Torso fat %",
    "mW": "Global muscle %",
    "mr": "Arm muscle (right) %",
    "ml": "Arm muscle (left) %",
    "mR": "Leg muscle (right)%",
    "mL": "Leg muscle (left) %",
    "mT": "Torso muscle %",
    "bW": "Estimated bone mass",
    "IF": "Visceral fat rating",
    "rA": "Estimated metabolic age",
    "rD": "Daily calorie intake (DCI)",
    "ww": "Global body water %",
    # "CS": "Unknown: BC, this does change per entry",
}
